### ISSUE TITLE
За что отвечает это поле?

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework3Burgers#2]
https://github.com/HelgaJava/git-homework3Burgers/blob/e60cfb1303ec738aeadecfee185599dbcbbf6563/src/test/java/Product.java#L8

**Comment by HelgaJava** [comment]
Убрала. Предполагалось, что оно отвечает за кол-во заказанных бургеров. Я думала, что это страница заказа из-за знака "+" рядом с бургером. Проверила теперь, это оказывается просто переход на подробное описание. Поэтому смысла в этом поле нет
